spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/crud}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1Rlfdlrlflqlc?}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  main:
    allow-bean-definition-overriding: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false

  jwt:
    secret-key: ${JWT_SECRET_KEY}
